// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/arvindnama/golang-microservices/order-service/sdk/models"
)

// NewPatchOrderParams creates a new PatchOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchOrderParams() *PatchOrderParams {
	return &PatchOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchOrderParamsWithTimeout creates a new PatchOrderParams object
// with the ability to set a timeout on a request.
func NewPatchOrderParamsWithTimeout(timeout time.Duration) *PatchOrderParams {
	return &PatchOrderParams{
		timeout: timeout,
	}
}

// NewPatchOrderParamsWithContext creates a new PatchOrderParams object
// with the ability to set a context for a request.
func NewPatchOrderParamsWithContext(ctx context.Context) *PatchOrderParams {
	return &PatchOrderParams{
		Context: ctx,
	}
}

// NewPatchOrderParamsWithHTTPClient creates a new PatchOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchOrderParamsWithHTTPClient(client *http.Client) *PatchOrderParams {
	return &PatchOrderParams{
		HTTPClient: client,
	}
}

/*
PatchOrderParams contains all the parameters to send to the API endpoint

	for the patch order operation.

	Typically these are written to a http.Request.
*/
type PatchOrderParams struct {

	/* Body.

	   A order in DB
	*/
	Body *models.Order

	/* ID.

	   Id of the product

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchOrderParams) WithDefaults() *PatchOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch order params
func (o *PatchOrderParams) WithTimeout(timeout time.Duration) *PatchOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch order params
func (o *PatchOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch order params
func (o *PatchOrderParams) WithContext(ctx context.Context) *PatchOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch order params
func (o *PatchOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch order params
func (o *PatchOrderParams) WithHTTPClient(client *http.Client) *PatchOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch order params
func (o *PatchOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch order params
func (o *PatchOrderParams) WithBody(body *models.Order) *PatchOrderParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch order params
func (o *PatchOrderParams) SetBody(body *models.Order) {
	o.Body = body
}

// WithID adds the id to the patch order params
func (o *PatchOrderParams) WithID(id int64) *PatchOrderParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch order params
func (o *PatchOrderParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
