// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/arvindnama/golang-microservices/order-service/sdk/models"
)

// CreateOrderReader is a Reader for the CreateOrder structure.
type CreateOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateOrderCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateOrderUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateOrderInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /orders] createOrder", response, response.Code())
	}
}

// NewCreateOrderCreated creates a CreateOrderCreated with default headers values
func NewCreateOrderCreated() *CreateOrderCreated {
	return &CreateOrderCreated{}
}

/*
CreateOrderCreated describes a response with status code 201, with default header values.

A orders
*/
type CreateOrderCreated struct {
	Payload *models.Order
}

// IsSuccess returns true when this create order created response has a 2xx status code
func (o *CreateOrderCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create order created response has a 3xx status code
func (o *CreateOrderCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create order created response has a 4xx status code
func (o *CreateOrderCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create order created response has a 5xx status code
func (o *CreateOrderCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create order created response a status code equal to that given
func (o *CreateOrderCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create order created response
func (o *CreateOrderCreated) Code() int {
	return 201
}

func (o *CreateOrderCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orders][%d] createOrderCreated %s", 201, payload)
}

func (o *CreateOrderCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orders][%d] createOrderCreated %s", 201, payload)
}

func (o *CreateOrderCreated) GetPayload() *models.Order {
	return o.Payload
}

func (o *CreateOrderCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Order)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrderUnauthorized creates a CreateOrderUnauthorized with default headers values
func NewCreateOrderUnauthorized() *CreateOrderUnauthorized {
	return &CreateOrderUnauthorized{}
}

/*
CreateOrderUnauthorized describes a response with status code 401, with default header values.

CreateOrderUnauthorized create order unauthorized
*/
type CreateOrderUnauthorized struct {
	Payload *models.ValidationError
}

// IsSuccess returns true when this create order unauthorized response has a 2xx status code
func (o *CreateOrderUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create order unauthorized response has a 3xx status code
func (o *CreateOrderUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create order unauthorized response has a 4xx status code
func (o *CreateOrderUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create order unauthorized response has a 5xx status code
func (o *CreateOrderUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create order unauthorized response a status code equal to that given
func (o *CreateOrderUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create order unauthorized response
func (o *CreateOrderUnauthorized) Code() int {
	return 401
}

func (o *CreateOrderUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orders][%d] createOrderUnauthorized %s", 401, payload)
}

func (o *CreateOrderUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orders][%d] createOrderUnauthorized %s", 401, payload)
}

func (o *CreateOrderUnauthorized) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *CreateOrderUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrderInternalServerError creates a CreateOrderInternalServerError with default headers values
func NewCreateOrderInternalServerError() *CreateOrderInternalServerError {
	return &CreateOrderInternalServerError{}
}

/*
CreateOrderInternalServerError describes a response with status code 500, with default header values.

CreateOrderInternalServerError create order internal server error
*/
type CreateOrderInternalServerError struct {
	Payload *models.ValidationError
}

// IsSuccess returns true when this create order internal server error response has a 2xx status code
func (o *CreateOrderInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create order internal server error response has a 3xx status code
func (o *CreateOrderInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create order internal server error response has a 4xx status code
func (o *CreateOrderInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create order internal server error response has a 5xx status code
func (o *CreateOrderInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create order internal server error response a status code equal to that given
func (o *CreateOrderInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create order internal server error response
func (o *CreateOrderInternalServerError) Code() int {
	return 500
}

func (o *CreateOrderInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orders][%d] createOrderInternalServerError %s", 500, payload)
}

func (o *CreateOrderInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orders][%d] createOrderInternalServerError %s", 500, payload)
}

func (o *CreateOrderInternalServerError) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *CreateOrderInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
