basePath: /
consumes:
    - application/json
definitions:
    GenericError:
        x-go-package: build-go-microservice/handlers
    Product:
        description: Product defines the structure for an API products
        x-go-package: build-go-microservice/data
    ValidationError:
        description: ValidationError is a collection error messages
        x-go-package: build-go-microservice/handlers
info:
    description: Documentation for Product API
    title: of Product API
    version: 1.0.0
paths:
    /products:
        get:
            description: Returns a list of products
            operationId: listProducts
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
            tags:
                - products
        post:
            description: Add a product into the database
            operationId: createProduct
            responses:
                "200":
                    $ref: '#/responses/noContentResponse'
                "422":
                    $ref: '#/responses/errorValidation'
                "501":
                    $ref: '#/responses/errorResponse'
            tags:
                - products
    /products/{id}:
        delete:
            description: Deletes the product from the database
            operationId: deleteProduct
            parameters:
                - description: The id of the product to delete
                  format: int64
                  in: path
                  name: id
                  required: true
                  type: integer
                  x-go-name: ID
            responses:
                "200":
                    $ref: '#/responses/noContentResponse'
                "404":
                    $ref: '#/responses/errorResponse'
                "501":
                    $ref: '#/responses/errorResponse'
            tags:
                - products
        put:
            description: Update a products details
            operationId: updateProduct
            responses:
                "201":
                    $ref: '#/responses/noContentResponse'
                "404":
                    $ref: '#/responses/errorResponse'
                "422":
                    $ref: '#/responses/errorValidation'
            tags:
                - products
produces:
    - application/json
responses:
    errorResponse:
        description: Generic Error message as string
    errorValidation:
        description: Validation errors defined as array of string
    noContentResponse:
        description: ""
    productsResponse:
        description: A list of products
        schema:
            items: {}
            type: array
schemes:
    - http
swagger: "2.0"
