// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllOrdersParams creates a new GetAllOrdersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllOrdersParams() *GetAllOrdersParams {
	return &GetAllOrdersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllOrdersParamsWithTimeout creates a new GetAllOrdersParams object
// with the ability to set a timeout on a request.
func NewGetAllOrdersParamsWithTimeout(timeout time.Duration) *GetAllOrdersParams {
	return &GetAllOrdersParams{
		timeout: timeout,
	}
}

// NewGetAllOrdersParamsWithContext creates a new GetAllOrdersParams object
// with the ability to set a context for a request.
func NewGetAllOrdersParamsWithContext(ctx context.Context) *GetAllOrdersParams {
	return &GetAllOrdersParams{
		Context: ctx,
	}
}

// NewGetAllOrdersParamsWithHTTPClient creates a new GetAllOrdersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllOrdersParamsWithHTTPClient(client *http.Client) *GetAllOrdersParams {
	return &GetAllOrdersParams{
		HTTPClient: client,
	}
}

/*
GetAllOrdersParams contains all the parameters to send to the API endpoint

	for the get all orders operation.

	Typically these are written to a http.Request.
*/
type GetAllOrdersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllOrdersParams) WithDefaults() *GetAllOrdersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllOrdersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all orders params
func (o *GetAllOrdersParams) WithTimeout(timeout time.Duration) *GetAllOrdersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all orders params
func (o *GetAllOrdersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all orders params
func (o *GetAllOrdersParams) WithContext(ctx context.Context) *GetAllOrdersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all orders params
func (o *GetAllOrdersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all orders params
func (o *GetAllOrdersParams) WithHTTPClient(client *http.Client) *GetAllOrdersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all orders params
func (o *GetAllOrdersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllOrdersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
