// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/arvindnama/golang-microservices/product-api-service/sdk/models"
)

// ListProductsReader is a Reader for the ListProducts structure.
type ListProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 501:
		result := NewListProductsNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /products] listProducts", response, response.Code())
	}
}

// NewListProductsOK creates a ListProductsOK with default headers values
func NewListProductsOK() *ListProductsOK {
	return &ListProductsOK{}
}

/*
ListProductsOK describes a response with status code 200, with default header values.

A list of products
*/
type ListProductsOK struct {
	Payload *models.ProductsPaginatedResponse
}

// IsSuccess returns true when this list products o k response has a 2xx status code
func (o *ListProductsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list products o k response has a 3xx status code
func (o *ListProductsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list products o k response has a 4xx status code
func (o *ListProductsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list products o k response has a 5xx status code
func (o *ListProductsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list products o k response a status code equal to that given
func (o *ListProductsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list products o k response
func (o *ListProductsOK) Code() int {
	return 200
}

func (o *ListProductsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] listProductsOK %s", 200, payload)
}

func (o *ListProductsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] listProductsOK %s", 200, payload)
}

func (o *ListProductsOK) GetPayload() *models.ProductsPaginatedResponse {
	return o.Payload
}

func (o *ListProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProductsPaginatedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProductsNotImplemented creates a ListProductsNotImplemented with default headers values
func NewListProductsNotImplemented() *ListProductsNotImplemented {
	return &ListProductsNotImplemented{}
}

/*
ListProductsNotImplemented describes a response with status code 501, with default header values.

Generic Error message as string
*/
type ListProductsNotImplemented struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this list products not implemented response has a 2xx status code
func (o *ListProductsNotImplemented) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list products not implemented response has a 3xx status code
func (o *ListProductsNotImplemented) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list products not implemented response has a 4xx status code
func (o *ListProductsNotImplemented) IsClientError() bool {
	return false
}

// IsServerError returns true when this list products not implemented response has a 5xx status code
func (o *ListProductsNotImplemented) IsServerError() bool {
	return true
}

// IsCode returns true when this list products not implemented response a status code equal to that given
func (o *ListProductsNotImplemented) IsCode(code int) bool {
	return code == 501
}

// Code gets the status code for the list products not implemented response
func (o *ListProductsNotImplemented) Code() int {
	return 501
}

func (o *ListProductsNotImplemented) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] listProductsNotImplemented %s", 501, payload)
}

func (o *ListProductsNotImplemented) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] listProductsNotImplemented %s", 501, payload)
}

func (o *ListProductsNotImplemented) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *ListProductsNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
